{% set name = "chainmap" %}
{% set version = "1.0.3" %}
{% set sha256 = "e42aaa4b3e2f66102a11bfd563069704bfbfd84fdcb517b564effd736bf53cd9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - pytest
    - python {{ python_min }}
  imports:
    - chainmap
  files:
    - test_chainmap.py
  commands:
    - pytest --pyargs test_chainmap.py

about:
  home: https://bitbucket.org/jeunice/chainmap/overview
  license: PSFL
  license_file: LICENSE.txt
  summary: "Backport/clone of ChainMap for py26, py32, and pypy3"
  description: |
    This module is a polyfill, implementing ChainMap for reasonably-recent 
    versions of Python that do not have collections.ChainMap–namely, 
    Python 2.6, Python 3.2, and PyPy3 releases based on Python 3.2. 
    (It will also work as expected on Python 2.7, PyPy, and Python 3.3 and 
    higher, but it is not needed there since those verions’ collections modules 
    contains a ChainMap implementation.)
    The code for this package is closely derived from the Python 3.5 source 
    code at hg.python.org, (especially the collections and reprlib modules). 
    Several changes have been made to ensure Python 2.6 compatibility, and 
    tests and packaging have been added.
  dev_url: https://bitbucket.org/jeunice/chainmap/overview

extra:
  recipe-maintainers:
    - astamminger
