travis:
  secure:
    BINSTAR_TOKEN: EeIKy869aTi/cNz1NqD43c/WeIoK3cQLddRBcdag7SFEvIuXVIgbuiafeAv7M5SporK8i+EYOdvfHhzfKhIFARnWrAzqoF/KH2VCPmOZmiKfiShwn7E+dI/MltEqdmWdwIGAKUTIiVydUMUGpfCp709+6zzjZUfliyAZmZJx0dXqjNmMTcDVy9DVu/A8fknKMVttim3g5u0oHolP/McoPfNuyhkkpbR3u2og2ydhXEsiUS+ZveUfHwpRvxon1WWeOZaYa8MN7YEyygQNxhVoXPDyKSLubYu9ozZIBAjI/FamKwDiXB/6B/Ypzwuusw3GyyuYpNhJHOL78pXxVuTXBr5Vx86wb5ZMs59yDrBgPQT0X+G7kfoUtTrQLouL+p7orOPO1yw7Io8f+iFIn9IJ9M79OjU4IfzIK7Zg6g9CNIbZuyqMPFyP6eOOcORm7IAkU+Oca5mjNlL83W8zX4kIryVkXd7J78R5BFKg2vJuzfztiXzn8B8Ty8SS5fRefcJtb2RIIo6QLAnol93HGyoGhzEMBjJsKZ2Nnxwxt5pGS1nnx5laAYD+IUWR5gOcGBeL+GFSlCfyZZFuZ6c5V5XaVtQabDcpxgCMTN8eXU1zeNQyJMhpBfEZ/uacN5f+27DP6pZLf3n926U+3ieBX0sxN1fOCVrQ+2gaSrRbGXSvS+0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
